apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
commonLabels:
  app: video-analyser
commonAnnotations:
  boclips-version: "30"
images:
- name: app
  newName: eu.gcr.io/boclips-prod/boclips/video-analyser
  newTag: "30"
patches:
- path: spread-across-zones.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
- path: boot-time.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
- path: scale.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
vars:
- fieldref:
    fieldPath: metadata.annotations.boclips-version
  name: VERSION
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: video-analyser
