apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
namespace: staging
replicas:
- count: 1
  name: video-analyser
patches:
- path: domain.yaml
  target:
    group: extensions
    kind: Ingress
    version: v1beta1
- path: jaeger-service-name.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
- path: noncritical.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
- path: jvm-debugging.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
